In [1]:
import numpy as np
import pandas as pd

In [4]:
df=pd.read_csv(r'C:\Users\HP\OneDrive\Desktop\python\Pandad\Housing.csv')
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

Q1. Write a program to find the average price of houses grouped by the
number of bedrooms. Display the result in descending order of average price.

In [16]:
avg_num=df.groupby('bedrooms')['price'].mean()
s=avg_num.sort_values(ascending=False)
s

bedrooms
5    5.819800e+06
4    5.729758e+06
3    4.954598e+06
6    4.791500e+06
2    3.632022e+06
1    2.712500e+06
Name: price, dtype: float64

Q2. Create a program to calculate the total area of houses grouped by stories.
Display only the top 2 with the largest total area.

In [27]:
# total sum ka liya .sum use hota ha
s=df.groupby('stories')['area'].sum()
s1=s.sort_values(ascending=False).head(2)
s1

stories
1    1200790
2    1132153
Name: area, dtype: int64

Q3. Determine the maximum price of houses based on whether they have
hotwaterheating or not. Also display the data of both rows.

In [43]:
s=df.groupby('hotwaterheating')['price'].max()
result=df[df.apply(lambda row: row['price'] == s[row['hotwaterheating']],axis=1)]
result

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
11,9681000,6000,4,3,2,yes,yes,yes,yes,no,2,no,semi-furnished

4.  Add a column named PricePerSqFt to calculate the price per square foot for each house. Group the dataset by the number of floors and find the average PricePerSqFt for each group.

In [62]:
df['pricesqft']=df['price']/df['area']
df.groupby('stories')['pricesqft'].mean()

stories
1    5289.823789
2    4756.945378
3    5316.641026
4    6506.170732
Name: pricesqft, dtype: float64

Q5. Group the data by parking and count the total number of houses in each number of parking. Also sort in acsending order.

In [71]:
df.groupby('parking').size().sort_index()

parking
0    299
1    126
2    108
3     12
dtype: int64

Q6.  Write a program to group houses based on the number of bathrooms and find the minimum, maximum, and average area (square feet) for each bathroom group.

In [ ]:
# agg mean hota ha agrigration fun jo ek sath ma bouth sa fun ko call karta ha 
df.groupby('bathrooms')['area'].agg(['max','min','mean'])

                   max          min         mean
bathrooms
1          2278.215223   270.395550   933.644539
2          2640.000000   485.155684  1153.875178
3          1675.757576   626.543210  1213.915686
4          1367.187500  1367.187500  1367.187500

Q7. Perform all the attributes and methods of pandas groupby object on this dataset which are discussed in class and analyse the data.

In [84]:
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,pricesqft
0,13300000,1792.452830,4,2,3,yes,no,no,no,yes,2,yes,furnished,7420.0
1,12250000,1367.187500,4,4,4,yes,no,no,no,yes,3,no,furnished,8960.0
2,12250000,1229.919679,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished,9960.0
3,12215000,1628.666667,4,2,2,yes,no,yes,no,yes,3,yes,furnished,7500.0
4,11410000,1537.735849,4,1,2,yes,yes,yes,no,yes,2,no,furnished,7420.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,606.666667,2,1,1,yes,no,yes,no,no,2,no,unfurnished,3000.0
541,1767150,736.312500,3,1,1,no,no,no,no,no,0,no,semi-furnished,2400.0
542,1750000,483.425414,2,1,1,yes,no,no,no,no,0,no,unfurnished,3620.0
543,1750000,601.374570,3,1,1,no,no,no,no,no,0,no,furnished,2910.0
544,1750000,454.545455,3,1,2,yes,no,no,no,no,0,no,unfurnished,3850.0

In [87]:
group=df.groupby('area')
group

In [88]:
group.size()

area
270.395550     1
318.181818     1
350.000000     1
368.421053     1
373.043478     1
              ..
1958.041958    1
1963.218391    1
2025.462963    1
2278.215223    1
2640.000000    1
Length: 506, dtype: int64

In [89]:
group.ngroup()

0      492
1      435
2      401
3      472
4      462
      ...
540     59
541    122
542     23
543     58
544     14
Length: 545, dtype: int64

In [92]:
group.indices

{np.float64(270.39555006180467): array([403]),
 np.float64(318.1818181818182): array([520]),
 np.float64(350.0): array([452]),
 np.float64(368.42105263157896): array([401]),
 np.float64(373.04347826086956): array([473]),
 np.float64(379.84496124031006): array([211]),
 np.float64(380.96153846153845): array([125]),
 np.float64(381.1111111111111): array([460]),
 np.float64(401.47058823529414): array([494]),
 np.float64(415.5405405405405): array([277]),
 np.float64(421.3207547169811): array([531]),
 np.float64(444.44444444444446): array([483]),
 np.float64(447.85276073619633): array([186]),
 np.float64(450.0): array([354]),
 np.float64(454.54545454545456): array([544]),
 np.float64(457.3333333333333): array([355]),
 np.float64(457.9107505070994): array([252]),
 np.float64(464.84375): array([224]),
 np.float64(466.6666666666667): array([451]),
 np.float64(471.02803738317755): array([191]),
 np.float64(471.4439655172414): array([393]),
 np.float64(476.1904761904762): array([399]),
 np.float64(478.3333333333333): array([486]),
 np.float64(483.42541436464086): array([542]),
 np.float64(485.1485148514852): array([336]),
 np.float64(485.15568428674874): array([229]),
 np.float64(502.56410256410254): array([476]),
 np.float64(506.198347107438): array([519]),
 np.float64(508.24242424242425): array([304]),
 np.float64(511.2474437627812): array([171]),
 np.float64(512.478184991274): array([129]),
 np.float64(517.9501233214579): array([538]),
 np.float64(519.3104953087498): array([222]),
 np.float64(525.0): array([66]),
 np.float64(531.4814814814815): array([487]),
 np.float64(533.3333333333334): array([142, 146]),
 np.float64(535.7142857142857): array([175]),
 np.float64(538.3109619686801): array([342]),
 np.float64(539.9449035812672): array([331]),
 np.float64(541.6666666666666): array([247]),
 np.float64(542.9042904290429): array([432]),
 np.float64(543.030303030303): array([257]),
 np.float64(544.4444444444445): array([357]),
 np.float64(548.5576923076923): array([488]),
 np.float64(549.5495495495495): array([284]),
 np.float64(559.5238095238095): array([437]),
 np.float64(561.6211745244003): array([69]),
 np.float64(564.7727272727273): array([513]),
 np.float64(569.4267515923567): array([455]),
 np.float64(573.0478589420655): array([528, 529]),
 np.float64(573.0994152046784): array([536]),
 np.float64(588.6363636363636): array([508]),
 np.float64(591.9753086419753): array([220]),
 np.float64(592.741935483871): array([477]),
 np.float64(592.9866036249015): array([470]),
 np.float64(593.2203389830509): array([397]),
 np.float64(595.2380952380952): array([402]),
 np.float64(600.0): array([299]),
 np.float64(601.3745704467354): array([543]),
 np.float64(606.6666666666666): array([540]),
 np.float64(610.738255033557): array([375]),
 np.float64(614.1104294478528): array([194]),
 np.float64(615.7407407407408): array([327]),
 np.float64(616.1971830985915): array([176]),
 np.float64(616.2790697674419): array([361]),
 np.float64(620.4013377926422): array([539]),
 np.float64(620.9677419354839): array([461]),
 np.float64(625.0): array([172, 535]),
 np.float64(626.3982102908277): array([64]),
 np.float64(626.5432098765432): array([7]),
 np.float64(630.0): array([82]),
 np.float64(632.3284823284823): array([113]),
 np.float64(636.8421052631579): array([285]),
 np.float64(641.8706293706293): array([56]),
 np.float64(644.2307692307693): array([525]),
 np.float64(644.7368421052631): array([183]),
 np.float64(646.6302367941712): array([196]),
 np.float64(648.3704974271012): array([352]),
 np.float64(651.3157894736842): array([406]),
 np.float64(651.5957446808511): array([368]),
 np.float64(651.7241379310345): array([490]),
 np.float64(654.3478260869565): array([469]),
 np.float64(662.4484181568088): array([521]),
 np.float64(663.1578947368421): array([190]),
 np.float64(663.25): array([505]),
 np.float64(665.0): array([503]),
 np.float64(671.3836477987421): array([279, 280]),
 np.float64(672.8682170542636): array([274]),
 np.float64(673.75): array([496]),
 np.float64(676.1565836298932): array([497]),
 np.float64(677.4193548387096): array([419]),
 np.float64(679.4495412844037): array([365]),
 np.float64(680.3630363036303): array([311]),
 np.float64(682.0512820512821): array([166]),
 np.float64(682.5): array([495]),
 np.float64(683.59375): array([474]),
 np.float64(684.4444444444445): array([464]),
 np.float64(685.0): array([219]),
 np.float64(688.1355932203389): array([316]),
 np.float64(688.5964912280701): array([158]),
 np.float64(690.0584795321637): array([310]),
 np.float64(696.3350785340314): array([429]),
 np.float64(698.4444444444445): array([454]),
 np.float64(700.0): array([ 96, 518, 534]),
 np.float64(703.3018867924528): array([259]),
 np.float64(703.8764208685515): array([217]),
 np.float64(707.070707070707): array([493]),
 np.float64(707.3684210526316): array([421]),
 np.float64(709.5088819226751): array([415]),
 np.float64(711.6666666666666): array([532]),
 np.float64(712.7272727272727): array([332]),
 np.float64(712.8571428571429): array([404]),
 np.float64(717.9487179487179): array([289]),
 np.float64(719.4444444444445): array([507, 509]),
 np.float64(723.3333333333334): array([438]),
 np.float64(724.1379310344828): array([298]),
 np.float64(724.3055555555555): array([181]),
 np.float64(726.4150943396227): array([340, 526]),
 np.float64(727.4247491638796): array([111]),
 np.float64(729.1666666666666): array([209, 524]),
 np.float64(731.25): array([315]),
 np.float64(732.7823691460055): array([499]),
 np.float64(736.3125): array([541]),
 np.float64(736.8421052631579): array([441]),
 np.float64(738.0381086803105): array([178]),
 np.float64(738.0434782608696): array([225]),
 np.float64(742.4242424242424): array([10]),
 np.float64(745.3703703703703): array([323, 443]),
 np.float64(750.5827505827506): array([89]),
 np.float64(752.5): array([115]),
 np.float64(753.0454042081949): array([223]),
 np.float64(756.1728395061729): array([516]),
 np.float64(760.8695652173913): array([389]),
 np.float64(761.2574341546305): array([255]),
 np.float64(763.2398753894081): array([515]),
 np.float64(763.6363636363636): array([192, 287]),
 np.float64(764.3678160919541): array([502]),
 np.float64(769.2307692307693): array([448]),
 np.float64(777.7777777777778): array([205]),
 np.float64(780.4054054054054): array([65]),
 np.float64(781.6666666666666): array([227]),
 np.float64(784.2323651452282): array([349]),
 np.float64(789.0909090909091): array([85]),
 np.float64(790.2659307576517): array([446]),
 np.float64(790.633608815427): array([485]),
 np.float64(792.4528301886793): array([511]),
 np.float64(793.3333333333334): array([383, 384]),
 np.float64(794.8717948717949): array([163]),
 np.float64(796.1711711711712): array([61]),
 np.float64(799.6688741721854): array([216]),
 np.float64(800.4347826086956): array([156]),
 np.float64(801.1111111111111): array([380]),
 np.float64(801.3157894736842): array([465]),
 np.float64(802.6666666666666): array([471]),
 np.float64(802.7522935779816): array([169]),
 np.float64(803.2786885245902): array([164, 479]),
 np.float64(805.0): array([57]),
 np.float64(809.0909090909091): array([458]),
 np.float64(812.8415300546449): array([123]),
 np.float64(813.3012820512821): array([317]),
 np.float64(813.3802816901408): array([235]),
 np.float64(814.3564356435644): array([435]),
 np.float64(815.5339805825242): array([420]),
 np.float64(816.6666666666666): array([478, 517]),
 np.float64(821.2290502793296): array([126]),
 np.float64(822.8460793804453): array([121]),
 np.float64(823.019801980198): array([428]),
 np.float64(825.4716981132076): array([387]),
 np.float64(827.2727272727273): array([162]),
 np.float64(828.2442748091603): array([439]),
 np.float64(828.3333333333334): array([514]),
 np.float64(829.0): array([134]),
 np.float64(829.2011019283747): array([472]),
 np.float64(829.6906523201076): array([198]),
 np.float64(832.967032967033): array([504]),
 np.float64(833.3333333333334): array([288]),
 np.float64(834.5736434108527): array([165]),
 np.float64(837.7049180327868): array([187]),
 np.float64(840.0): array([512]),
 np.float64(844.8275862068965): array([206, 480]),
 np.float64(847.2772277227723): array([414]),
 np.float64(847.5783475783476): array([119]),
 np.float64(848.4848484848485): array([149]),
 np.float64(848.7237237237238): array([141]),
 np.float64(848.8805970149253): array([245]),
 np.float64(850.4672897196261): array([370]),
 np.float64(853.9648367420165): array([523]),
 np.float64(855.2631578947369): array([244]),
 np.float64(857.5): array([408]),
 np.float64(859.0909090909091): array([489]),
 np.float64(860.5371900826447): array([306]),
 np.float64(866.6115702479339): array([177]),
 np.float64(867.6160337552743): array([434]),
 np.float64(868.5185185185185): array([230]),
 np.float64(872.463768115942): array([116]),
 np.float64(873.8191632928475): array([88]),
 np.float64(875.0): array([ 93, 510, 533]),
 np.float64(877.1929824561404): array([392]),
 np.float64(879.2270531400966): array([160]),
 np.float64(880.503144654088): array([148]),
 np.float64(881.3559322033898): array([376]),
 np.float64(885.2525252525253): array([268]),
 np.float64(885.2941176470588): array([114]),
 np.float64(886.6666666666666): array([ 37, 328]),
 np.float64(887.2377622377622): array([188]),
 np.float64(888.4615384615385): array([440]),
 np.float64(890.0): array([459]),
 np.float64(890.5555555555555): array([324]),
 np.float64(890.9090909090909): array([410]),
 np.float64(891.6234887737478): array([309]),
 np.float64(894.8453608247422): array([506]),
 np.float64(894.9186991869918): array([267]),
 np.float64(895.0819672131148): array([161]),
 np.float64(895.4545454545455): array([67]),
 np.float64(896.0): array([423]),
 np.float64(900.0): array([264, 447]),
 np.float64(901.25): array([381]),
 np.float64(902.2540983606557): array([266]),
 np.float64(902.5157232704403): array([139]),
 np.float64(903.2258064516129): array([422]),
 np.float64(904.6153846153846): array([127]),
 np.float64(906.5573770491803): array([155]),
 np.float64(907.1566731141199): array([226]),
 np.float64(907.4074074074074): array([203]),
 np.float64(909.7859327217126): array([120]),
 np.float64(910.4208416833667): array([249]),
 np.float64(911.8773946360153): array([124]),
 np.float64(913.0434782608696): array([296, 445, 450]),
 np.float64(916.0493827160494): array([362]),
 np.float64(918.1818181818181): array([386]),
 np.float64(918.3168316831683): array([360]),
 np.float64(920.6349206349206): array([109]),
 np.float64(922.1556886227545): array([237]),
 np.float64(922.7272727272727): array([110]),
 np.float64(926.791277258567): array([118]),
 np.float64(929.0123456790124): array([467]),
 np.float64(932.6923076923077): array([417]),
 np.float64(933.3333333333334): array([303, 482]),
 np.float64(935.483870967742): array([318]),
 np.float64(938.8020833333334): array([58]),
 np.float64(939.8148148148148): array([320]),
 np.float64(943.6274509803922): array([343]),
 np.float64(943.939393939394): array([100]),
 np.float64(944.078947368421): array([484]),
 np.float64(945.4022988505748): array([433]),
 np.float64(946.4788732394367): array([27]),
 np.float64(948.8888888888889): array([281]),
 np.float64(950.0): array([500]),
 np.float64(950.9629629629629): array([91]),
 np.float64(951.3911096897986): array([122]),
 np.float64(952.3809523809524): array([293]),
 np.float64(953.4848484848485): array([98]),
 np.float64(954.0498442367601): array([107]),
 np.float64(954.5454545454545): array([170]),
 np.float64(958.9041095890411): array([388]),
 np.float64(960.0): array([418]),
 np.float64(961.5384615384615): array([396]),
 np.float64(961.6161616161617): array([522]),
 np.float64(962.5): array([135]),
 np.float64(964.4444444444445): array([270]),
 np.float64(972.2222222222222): array([395]),
 np.float64(973.170731707317): array([326]),
 np.float64(974.1100323624595): array([466]),
 np.float64(974.4318181818181): array([24]),
 np.float64(975.5905511811023): array([103]),
 np.float64(976.0119940029984): array([86]),
 np.float64(978.4090909090909): array([276]),
 np.float64(979.3577981651376): array([283]),
 np.float64(979.5795795795796): array([213]),
 np.float64(980.7692307692307): array([385]),
 np.float64(984.0579710144928): array([416]),
 np.float64(984.375): array([97]),
 np.float64(985.1851851851852): array([330]),
 np.float64(987.0): array([475]),
 np.float64(989.6551724137931): array([140]),
 np.float64(990.566037735849): array([173]),
 np.float64(993.3481152993348): array([254]),
 np.float64(996.5831435079726): array([400]),
 np.float64(996.7637540453075): array([463]),
 np.float64(996.9114619080302): array([131]),
 np.float64(997.3118279569892): array([49, 50]),
 np.float64(1000.0): array([344]),
 np.float64(1003.1152647975077): array([218]),
 np.float64(1005.7471264367816): array([394]),
 np.float64(1007.5757575757576): array([329]),
 np.float64(1012.396694214876): array([366, 367]),
 np.float64(1012.8787878787879): array([73]),
 np.float64(1013.6138613861386): array([314]),
 np.float64(1018.1818181818181): array([147]),
 np.float64(1019.6078431372549): array([371]),
 np.float64(1020.8333333333334): array([307, 369]),
 np.float64(1022.8381374722838): array([238]),
 np.float64(1023.0769230769231): array([77]),
 np.float64(1026.392961876833): array([453]),
 np.float64(1027.2536687631027): array([204, 335]),
 np.float64(1027.7777777777778): array([338]),
 np.float64(1029.4117647058824): array([308]),
 np.float64(1029.6641333660211): array([300]),
 np.float64(1030.5555555555557): array([152, 359]),
 np.float64(1032.051282051282): array([444]),
 np.float64(1032.1022727272727): array([379]),
 np.float64(1034.090909090909): array([374]),
 np.float64(1034.5911949685535): array([431]),
 np.float64(1035.15625): array([363]),
 np.float64(1035.8255451713396): array([76]),
 np.float64(1038.3333333333333): array([457]),
 np.float64(1044.1666666666667): array([99]),
 np.float64(1048.5416666666667): array([193]),
 np.float64(1050.0): array([ 94, 294, 351]),
 np.float64(1054.1176470588234): array([17]),
 np.float64(1054.6706844597504): array([210]),
 np.float64(1054.9450549450548): array([425]),
 np.float64(1056.6037735849056): array([ 28, 492]),
 np.float64(1061.7283950617284): array([468]),
 np.float64(1062.962962962963): array([136]),
 np.float64(1065.0306748466257): array([272]),
 np.float64(1067.8181818181818): array([128]),
 np.float64(1071.1805555555557): array([275]),
 np.float64(1073.8636363636363): array([491]),
 np.float64(1073.9130434782608): array([22]),
 np.float64(1074.979951884523): array([36]),
 np.float64(1076.1494252873563): array([358]),
 np.float64(1076.923076923077): array([409]),
 np.float64(1083.8709677419354): array([424]),
 np.float64(1084.070796460177): array([200]),
 np.float64(1085.648148148148): array([231]),
 np.float64(1088.888888888889): array([481]),
 np.float64(1090.342679127726): array([150]),
 np.float64(1094.6502057613168): array([501]),
 np.float64(1096.6666666666667): array([83]),
 np.float64(1104.8333333333333): array([80]),
 np.float64(1105.2631578947369): array([350]),
 np.float64(1106.132075471698): array([63]),
 np.float64(1108.0487804878048): array([248]),
 np.float64(1108.3333333333333): array([79]),
 np.float64(1108.8154269972451): array([321]),
 np.float64(1108.9108910891089): array([258]),
 np.float64(1110.576923076923): array([233]),
 np.float64(1111.391129032258): array([263]),
 np.float64(1111.764705882353): array([537]),
 np.float64(1112.7717391304348): array([313]),
 np.float64(1117.3076923076924): array([132]),
 np.float64(1118.3908045977012): array([214]),
 np.float64(1120.0): array([145, 256]),
 np.float64(1121.7948717948718): array([269, 398]),
 np.float64(1123.7458193979933): array([30]),
 np.float64(1125.8333333333333): array([71]),
 np.float64(1126.3636363636363): array([102, 104]),
 np.float64(1126.984126984127): array([195]),
 np.float64(1130.2752293577983): array([106]),
 np.float64(1132.3529411764705): array([405]),
 np.float64(1132.7272727272727): array([101]),
 np.float64(1133.0128205128206): array([62]),
 np.float64(1133.3333333333333): array([382]),
 np.float64(1134.8484848484848): array([47]),
 np.float64(1138.4722222222222): array([312]),
 np.float64(1143.3333333333333): array([68]),
 np.float64(1144.6540880503144): array([372]),
 np.float64(1145.0746268656717): array([347]),
 np.float64(1146.25): array([239]),
 np.float64(1148.0): array([138]),
 np.float64(1148.7179487179487): array([530]),
 np.float64(1148.9130434782608): array([167]),
 np.float64(1152.832674571805): array([391]),
 np.float64(1153.8461538461538): array([297]),
 np.float64(1154.42): array([35]),
 np.float64(1158.236994219653): array([325]),
 np.float64(1158.888888888889): array([180]),
 np.float64(1161.0576923076924): array([215]),
 np.float64(1163.2947976878613): array([322]),
 np.float64(1166.6666666666667): array([ 78, 143]),
 np.float64(1168.3333333333333): array([199]),
 np.float64(1173.1225296442688): array([51]),
 np.float64(1182.983682983683): array([6]),
 np.float64(1184.6153846153845): array([14]),
 np.float64(1185.3333333333333): array([262]),
 np.float64(1186.8589743589744): array([364]),
 np.float64(1187.1345029239767): array([34]),
 np.float64(1188.2716049382716): array([42]),
 np.float64(1189.3203883495146): array([202]),
 np.float64(1190.0): array([60]),
 np.float64(1190.721649484536): array([234]),
 np.float64(1191.4893617021276): array([144, 334]),
 np.float64(1193.1818181818182): array([301]),
 np.float64(1194.0104166666667): array([240]),
 np.float64(1196.5811965811965): array([201]),
 np.float64(1199.7019374068554): array([442]),
 np.float64(1200.0): array([31]),
 np.float64(1201.6666666666667): array([59]),
 np.float64(1202.2900763358778): array([40]),
 np.float64(1210.1063829787233): array([241]),
 np.float64(1210.4166666666667): array([133]),
 np.float64(1210.691823899371): array([341]),
 np.float64(1211.111111111111): array([348]),
 np.float64(1213.1376659678547): array([21]),
 np.float64(1213.3333333333333): array([373]),
 np.float64(1215.3623188405797): array([305]),
 np.float64(1218.5185185185185): array([8]),
 np.float64(1221.698113207547): array([339]),
 np.float64(1222.0833333333333): array([130]),
 np.float64(1225.0): array([52, 54, 55]),
 np.float64(1229.9196787148594): array([2]),
 np.float64(1232.394366197183): array([168]),
 np.float64(1232.7044025157234): array([41]),
 np.float64(1237.0689655172414): array([137]),
 np.float64(1239.1067538126363): array([527]),
 np.float64(1240.0): array([273]),
 np.float64(1241.851851851852): array([426]),
 np.float64(1242.9906542056074): array([232]),
 np.float64(1250.0): array([242]),
 np.float64(1254.1666666666667): array([46]),
 np.float64(1257.9411764705883): array([278]),
 np.float64(1260.0): array([44, 45]),
 np.float64(1264.7727272727273): array([151]),
 np.float64(1274.3589743589744): array([261]),
 np.float64(1277.1929824561403): array([377]),
 np.float64(1282.6704545454545): array([253]),
 np.float64(1283.3333333333333): array([43]),
 np.float64(1286.3247863247864): array([250]),
 np.float64(1288.0): array([90]),
 np.float64(1292.0110192837465): array([228]),
 np.float64(1292.6136363636363): array([246]),
 np.float64(1300.604670558799): array([456]),
 np.float64(1305.8103975535169): array([25]),
 np.float64(1306.6666666666667): array([333]),
 np.float64(1308.695652173913): array([251]),
 np.float64(1314.176245210728): array([412]),
 np.float64(1316.0): array([430]),
 np.float64(1318.3333333333333): array([39]),
 np.float64(1323.5294117647059): array([353]),
 np.float64(1327.0833333333333): array([38]),
 np.float64(1330.0): array([498]),
 np.float64(1334.375): array([92]),
 np.float64(1338.6454183266933): array([72]),
 np.float64(1353.3333333333333): array([319]),
 np.float64(1367.1875): array([1]),
 np.float64(1368.888888888889): array([105]),
 np.float64(1374.1610738255033): array([33]),
 np.float64(1378.7878787878788): array([16]),
 np.float64(1379.2834890965732): array([19]),
 np.float64(1381.578947368421): array([174]),

In [93]:
group.min()

,price,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,pricesqft
area,,,,,,,,,,,,,
270.395550,3500000,3,1,1,yes,no,no,no,no,0,no,unfurnished,12944.0
318.181818,2450000,2,1,1,yes,no,no,no,no,0,no,unfurnished,7700.0
350.000000,3150000,3,1,2,yes,no,no,no,no,2,no,semi-furnished,9000.0
368.421053,3500000,3,1,2,yes,no,no,no,no,3,yes,unfurnished,9500.0
373.043478,3003000,2,1,1,yes,no,no,no,no,0,no,unfurnished,8050.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1958.041958,4200000,3,1,3,yes,no,no,no,no,1,yes,unfurnished,2145.0
1963.218391,4270000,3,1,2,no,yes,yes,no,yes,0,no,unfurnished,2175.0
2025.462963,8750000,3,1,2,yes,no,yes,yes,no,2,no,semi-furnished,4320.0
2278.215223,4340000,5,1,2,no,no,yes,no,no,0,no,semi-furnished,1905.0
2640.000000,9240000,4,2,2,yes,no,no,yes,no,2,no,furnished,3500.0

In [94]:
group.max()

,price,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,pricesqft
area,,,,,,,,,,,,,
270.395550,3500000,3,1,1,yes,no,no,no,no,0,no,unfurnished,12944.0
318.181818,2450000,2,1,1,yes,no,no,no,no,0,no,unfurnished,7700.0
350.000000,3150000,3,1,2,yes,no,no,no,no,2,no,semi-furnished,9000.0
368.421053,3500000,3,1,2,yes,no,no,no,no,3,yes,unfurnished,9500.0
373.043478,3003000,2,1,1,yes,no,no,no,no,0,no,unfurnished,8050.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1958.041958,4200000,3,1,3,yes,no,no,no,no,1,yes,unfurnished,2145.0
1963.218391,4270000,3,1,2,no,yes,yes,no,yes,0,no,unfurnished,2175.0
2025.462963,8750000,3,1,2,yes,no,yes,yes,no,2,no,semi-furnished,4320.0
2278.215223,4340000,5,1,2,no,no,yes,no,no,0,no,semi-furnished,1905.0
2640.000000,9240000,4,2,2,yes,no,no,yes,no,2,no,furnished,3500.0

In [95]:
group.first()

,price,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,pricesqft
area,,,,,,,,,,,,,
270.395550,3500000,3,1,1,yes,no,no,no,no,0,no,unfurnished,12944.0
318.181818,2450000,2,1,1,yes,no,no,no,no,0,no,unfurnished,7700.0
350.000000,3150000,3,1,2,yes,no,no,no,no,2,no,semi-furnished,9000.0
368.421053,3500000,3,1,2,yes,no,no,no,no,3,yes,unfurnished,9500.0
373.043478,3003000,2,1,1,yes,no,no,no,no,0,no,unfurnished,8050.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1958.041958,4200000,3,1,3,yes,no,no,no,no,1,yes,unfurnished,2145.0
1963.218391,4270000,3,1,2,no,yes,yes,no,yes,0,no,unfurnished,2175.0
2025.462963,8750000,3,1,2,yes,no,yes,yes,no,2,no,semi-furnished,4320.0
2278.215223,4340000,5,1,2,no,no,yes,no,no,0,no,semi-furnished,1905.0
2640.000000,9240000,4,2,2,yes,no,no,yes,no,2,no,furnished,3500.0

In [96]:
group.last()

,price,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,pricesqft
area,,,,,,,,,,,,,
270.395550,3500000,3,1,1,yes,no,no,no,no,0,no,unfurnished,12944.0
318.181818,2450000,2,1,1,yes,no,no,no,no,0,no,unfurnished,7700.0
350.000000,3150000,3,1,2,yes,no,no,no,no,2,no,semi-furnished,9000.0
368.421053,3500000,3,1,2,yes,no,no,no,no,3,yes,unfurnished,9500.0
373.043478,3003000,2,1,1,yes,no,no,no,no,0,no,unfurnished,8050.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1958.041958,4200000,3,1,3,yes,no,no,no,no,1,yes,unfurnished,2145.0
1963.218391,4270000,3,1,2,no,yes,yes,no,yes,0,no,unfurnished,2175.0
2025.462963,8750000,3,1,2,yes,no,yes,yes,no,2,no,semi-furnished,4320.0
2278.215223,4340000,5,1,2,no,no,yes,no,no,0,no,semi-furnished,1905.0
2640.000000,9240000,4,2,2,yes,no,no,yes,no,2,no,furnished,3500.0

Que 8= Write a python which display the name and data of the individual group and perform groupby on furnidhing status column of the data

In [108]:
s=df.groupby('furnishingstatus')

for i,j in s:
    print(i)
    print(j)

furnished
        price         area  bedrooms  bathrooms  stories mainroad guestroom  \
0    13300000  1792.452830         4          2        3      yes        no
1    12250000  1367.187500         4          4        4      yes        no
3    12215000  1628.666667         4          2        2      yes        no
4    11410000  1537.735849         4          1        2      yes       yes
8     9870000  1218.518519         4          1        2      yes       yes
..        ...          ...       ...        ...      ...      ...       ...
509   2590000   719.444444         2          2        2      yes        no
512   2520000   840.000000         2          1        2      yes        no
522   2380000   961.616162         3          1        2      yes        no
523   2380000   853.964837         4          2        2      yes        no
543   1750000   601.374570         3          1        1       no        no

    basement hotwaterheating airconditioning  parking prefarea  \
0         no              no             yes        2      yes
1         no              no             yes        3       no
3        yes              no             yes        3      yes
4        yes              no             yes        2       no
8        yes              no             yes        2      yes
..       ...             ...             ...      ...      ...
509      yes              no              no        1       no
512       no              no              no        0       no
522       no              no              no        0       no
523       no              no              no        0       no
543       no              no              no        0       no

    furnishingstatus  pricesqft
0          furnished     7420.0
1          furnished     8960.0
3          furnished     7500.0
4          furnished     7420.0
8          furnished     8100.0
..               ...        ...
509        furnished     3600.0
512        furnished     3000.0
522        furnished     2475.0
523        furnished     2787.0
543        furnished     2910.0

[140 rows x 14 columns]
semi-furnished
        price         area  bedrooms  bathrooms  stories mainroad guestroom  \
2    12250000  1229.919679         3          2        2      yes        no
5    10850000  1446.666667         3          3        1      yes        no
6    10150000  1182.983683         4          3        4      yes        no
11    9681000  1613.500000         4          3        2      yes       yes
12    9310000  1421.374046         4          2        2      yes        no
..        ...          ...       ...        ...      ...      ...       ...
502   2660000   764.367816         2          1        1      yes        no
503   2660000   665.000000         3          1        1      yes        no
514   2485000   828.333333         3          1        2       no        no
527   2275000  1239.106754         2          1        1       no        no
541   1767150   736.312500         3          1        1       no        no

    basement hotwaterheating airconditioning  parking prefarea  \
2        yes              no              no        2      yes
5        yes              no             yes        2      yes
6         no              no             yes        2      yes
11       yes             yes              no        2       no
12        no              no             yes        1      yes
..       ...             ...             ...      ...      ...
502       no              no              no        1       no
503       no              no              no        0       no
514       no              no              no        0       no
527      yes              no              no        0       no
541       no              no              no        0       no

    furnishingstatus  pricesqft
2     semi-furnished     9960.0
5     semi-furnished     7500.0
6     semi-furnished     8580.0
11    semi-furnished     6000.0
12    semi-furnished     6550.0
..               ...        ...
502   semi-furnished     3480.0
503   semi-furnished     4000.0
514   semi-furnished     3000.0
527   semi-furnished     1836.0
541   semi-furnished     2400.0

[227 rows x 14 columns]
unfurnished
        price         area  bedrooms  bathrooms  stories mainroad guestroom  \
7    10150000   626.543210         5          3        2      yes        no
9     9800000  1704.347826         3          2        4      yes       yes
16    9100000  1378.787879         4          2        2      yes       yes
21    8680000  1213.137666         3          2        1      yes       yes
28    8400000  1056.603774         5          2        2      yes        no
..        ...          ...       ...        ...      ...      ...       ...
538   1890000   517.950123         2          1        1      yes        no
539   1855000   620.401338         2          1        1       no        no
540   1820000   606.666667         2          1        1      yes        no
542   1750000   483.425414         2          1        1      yes        no
544   1750000   454.545455         3          1        2      yes        no

    basement hotwaterheating airconditioning  parking prefarea  \
7         no              no              no        0       no
9         no              no             yes        1      yes
16       yes              no             yes        1      yes
21       yes              no             yes        2       no
28       yes             yes              no        2       no
..       ...             ...             ...      ...      ...
538       no              no              no        0       no
539       no              no              no        1       no
540      yes              no              no        2       no
542       no              no              no        0       no
544       no              no              no        0       no

    furnishingstatus  pricesqft
7        unfurnished    16200.0
9        unfurnished     5750.0
16       unfurnished     6600.0
21       unfurnished     7155.0
28       unfurnished     7950.0
..               ...        ...
538      unfurnished     3649.0
539      unfurnished     2990.0
540      unfurnished     3000.0
542      unfurnished     3620.0
544      unfurnished     3850.0

[178 rows x 14 columns]