In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import make_regression

import plotly.express as px
import plotly.graph_objects as go

from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [2]:
x,y=make_regression(n_samples=100,n_features=2,n_informative=2,n_targets=1,noise=50)

In [3]:
df=pd.DataFrame({'feature1':x[:,0],'feature2':x[:,1],'target':y})

In [4]:
df.head()

   feature1  feature2      target
0 -1.084743 -0.131251   55.550708
1 -0.007665  0.584190   83.398362
2 -2.556062 -2.015355 -174.845720
3  0.346501  0.227955    9.933925
4 -0.319541 -1.355885  -43.015388

In [5]:
df.shape

(100, 3)

In [6]:
df.head()

   feature1  feature2      target
0 -1.084743 -0.131251   55.550708
1 -0.007665  0.584190   83.398362
2 -2.556062 -2.015355 -174.845720
3  0.346501  0.227955    9.933925
4 -0.319541 -1.355885  -43.015388

In [7]:
fig=px.scatter_3d(df,x='feature1',y='feature2',z='target')

In [8]:
! pip install nbformat

Requirement already satisfied: nbformat in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (5.10.4)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from nbformat) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from nbformat) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\hp\appdata\roaming\python\python312\site-packages (from nbformat) (5.7.2)
Requirement already satisfied: traitlets>=5.1 in c:\users\hp\appdata\roaming\python\python312\site-packages (from nbformat) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from jsonschema>=2.6->nbformat) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from jsonschema>=2.6->nbformat) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from jsonschema>=2.6->nbformat) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\hp\appdata\roaming\python\python312\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.2.2)
Requirement already satisfied: pywin32>=300 in c:\users\hp\appdata\roaming\python\python312\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (306)
Requirement already satisfied: typing-extensions>=4.4.0 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat) (4.15.0)

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
fig.show()

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=3,test_size=0.2)

In [12]:
from sklearn.linear_model import LinearRegression

lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [13]:
y_pred =lr.predict(x_test)

In [14]:
print("MAE",mean_absolute_error(y_test,y_pred))
print("MSE",mean_squared_error(y_test,y_pred))
print("r2_score",r2_score(y_test,y_pred))

MAE 50.56833112036277
MSE 3630.5565022453106
r2_score 0.6092385116565081

In [18]:
import numpy as np

# create grid
x = np.linspace(-5, 5, 10)
y = np.linspace(-5, 5, 10)

xGrid, yGrid = np.meshgrid(x, y)

# create input data for prediction
final = np.vstack((
    xGrid.ravel(),
    yGrid.ravel()
)).T

# prediction
z_final = lr.predict(final).reshape(10, 10)

z = z_final

In [22]:
import plotly.express as px
import plotly.graph_objects as go

# 3D scatter (actual data)
fig = px.scatter_3d(df,
                    x='feature1',
                    y='feature2',
                    z='target')

# Add regression surface
fig.add_trace(
    go.Surface(
        x=xGrid,
        y=yGrid,
        z=z
    )
)

fig.show()

In [23]:
lr.coef_

array([20.69655257, 53.86795615])

In [24]:
lr.intercept_

np.float64(-4.58062707766079)